### ISSUE TITLE
Further modifications

### ISSUE THREAD

**Issue by niccokunzmann** [kleinee/jns#3]
@kleinee, first of all thanks for providing the files. I am using them to automatically set up a notebook server.

I have some questions:

- is there a license stating your intention, how I may use your files?
- I used them and modified some of the scripts. Are you willing to accept pull-requests?

**Comment by kleinee** [comment]
I will add a MIT license - that should be flexible enough for most use cases including yours. Needless to say that the license that Project Jupyter is under should be observed under any circumstances. Changes that simplify or improve the process are more than welcome. Please share so that others can benefit .
