### ISSUE TITLE
Virtual environment should be activated before running 'inst_lab_ext.sh' script

### ISSUE THREAD

**Issue by dwblair** [kleinee/jns#33]
@kleinee -- Thank you *so* much for this setup -- it made getting Jupyter onto a Raspberry Pi so easy!

I noticed that the last line in the 'conf_jupyter.sh' script invokes the 'inst_lab_ext.sh' script.  I believe that the 'inst_lab_ext.sh' script won't work ('jupyter not found' messages) unless the virtual environment is activated first.  This means that the 'conf_jupyter.sh' fails on the last line of its script (which is 'bash -i ./inst_lab_ext.sh').  So after getting an error message at the end of the 'conf_jupyter.sh' execution, I simply invoked 'source /home/pi/.venv/jns/bin/activate'; after this, I was successfully able to use 'bash -i ./inst_lab_ext.sh' and proceed through your excellent README.  

Perhaps the fix would be simply to activate the virtual environment at the end of the 'conf_jupyter.sh' script, right before the 'bash -i ./inst_lab_ext.sh' line?  

Cheers, and thanks again so much for this wonderful documentation.

**Comment by kleinee** [comment]
Hi @dwblair, thanks for the positive feedback. I have not installed from scratch for a while but also did not change any of the scripts recently. Will test and update late next week as I am traveling for work in the moment. Glad you got it working. Enjoy! Will get back to you as soon as I tested.

**Comment by kleinee** [comment]
@deblair you are right. Take a look at the dev branch which is correct. Just add the activation of the environment to inst_lab_ext.sh and you are good to go. Will fix this as soon as I am back home. Eckhard

**Comment by dwblair** [comment]
Eckhard,

Wow -- that was so fast! :)  Thank you so much -- I'm actually using the revised scripts in the dev branch right now ... everything is going smoothly.  Thanks again for this great work.  Cheers!

- Don

**Comment by kleinee** [comment]
Hi @dwblair,

No idea why this issue was not reported earlier. Thanks for pointing me in the right direction so that others can enjoy a smooth installation. Your issue is fixed. 

Re-write of README.md for the dev branch is still pending. It has been quite a while now that I decided to go with the latest  system-installed Python 3 version to benefit from piwheels. Looking back this was the right move. The reported issue is fixed in master. As you might have seen in the scripts in the dev branch duration of the installation scripts is timed and results are written into a file as I wanted to get an idea how long the installation process takes on various pi models. I even tested installation on a Pi 1 with just 256MB of memory. piwheels is really a marvel of a service making this possible!

-Eckhard
