### ISSUE TITLE
Further performance improvements for headless use?

### ISSUE THREAD

**Issue by psychemedia** [kleinee/jns#5]
If using this as a headless Jupyter server (my use case), I wonder if optimisations aroun the `gpu_mem` setting would also be useful? eg as per something like http://raspberrypi.stackexchange.com/a/23976 ?  (I'm new to the Raspberry Pi so apols if this is a ridiculous statement!)

**Comment by kleinee** [comment]
Hi Tony,

Sorry for not mentioning this: I am using the notebook server headless as well and as such set GPU memory to 16MB (can conveniently done via raspi-config) since I first started setting up IPython on a Raspberry Pi 1 to maximize memory available to the system and minimize swapping. Back then this post of Arun Durvasula got me started: https://arundurvasula.wordpress.com/2014/04/01/remote-ipython-notebook-with-raspberry-pi/ <https://arundurvasula.wordpress.com/2014/04/01/remote-ipython-notebook-with-raspberry-pi/>. 

Eckhard

**Comment by psychemedia** [comment]
Hi Eckhard,

Thanks for letting me know.

I was also going to mention the possibility of adding the `rc.local` startup bit, which I note is in the original recipe?

Your guide is invaluable to folk who want to use Jupyter on a Pi but aren't interested in sysadmin (e.g. notebook users rather than commandline geeks!) and adding the startup line means, once built, folk can have a notebook server that "just runs":-)

(It's easy enough to then imagine having a wallet of SD cards that can just run other server based/browser consumed apps.)

Thanks again,
--tony

**Comment by kleinee** [comment]
Hi Tony,

Thanks for your feedback. I opted to start with j **jupyter notebook**  and stop with **CRTL-C**. Starting via rc.local is certainly possible but proper shutdown will require ssh login anyway.
Feel free to tweak at your heart's content.

Eckhard
